name: env382

dependencies:
 - python=3.8
 - anaconda==2020.11
 - matplotlib=3.3.2
 - pandas=1.1.3
 - lxml
 - requests=2.24.0 
 - git  
 - pip=20.2.4
 - pip:
   - pyxb==1.2.6
   - xmlschema==2.4.0
   - git+https://github.com/usnistgov/pycdcs
   - openpyxl==3.0.5
   - openpyxl-image-loader==1.0.5
   - qrcode==7.4.2
   
   
